"""Add back created_at

Revision ID: 8fdd3c974ff1
Revises: 903ba7c69746
Create Date: 2026-06-24 20:43:55.648200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdd3c974ff1'
down_revision: Union[str, Sequence[str], None] = '903ba7c69746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robots', 'created_at')
    # ### end Alembic commands ###
