"""Remove created_at

Revision ID: 903ba7c69746
Revises: c98b2e67d723
Create Date: 2026-06-24 12:21:55.575110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903ba7c69746'
down_revision: Union[str, Sequence[str], None] = 'c98b2e67d723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('robots', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('created_at', sa.DATETIME(), nullable=False))
    # ### end Alembic commands ###
